// <auto-generated />
using System;
using EntityFreamworkAssigment.E_Shop.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFreamworkAssigment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109105658_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Categories", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductsProductID")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.HasIndex("ProductsProductID");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Customrs", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrdersOrderID")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentInformationPaymentID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewsReviewID")
                        .HasColumnType("int");

                    b.Property<int?>("ShippingAddressesAddressID")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.HasIndex("OrdersOrderID");

                    b.HasIndex("PaymentInformationPaymentID");

                    b.HasIndex("ReviewsReviewID");

                    b.HasIndex("ShippingAddressesAddressID");

                    b.ToTable("customrs");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.OrderItems", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int>("ItemPrice")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("orderItems");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Orders", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderItemsOrderItemID")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("OrderItemsOrderItemID");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.PaymentInformation", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentID"));

                    b.Property<int>("CVV")
                        .HasColumnType("int");

                    b.Property<int>("CardNumber")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("paymentMethod")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("CustomerID");

                    b.ToTable("paymentInformation");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Products", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderItemsOrderItemID")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewsReviewID")
                        .HasColumnType("int");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("OrderItemsOrderItemID");

                    b.HasIndex("ReviewsReviewID");

                    b.ToTable("products");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Reviews", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ProductID");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.ShippingAddresses", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressID");

                    b.HasIndex("CustomerID");

                    b.ToTable("shippingAddresses");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Categories", b =>
                {
                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Products", null)
                        .WithMany("categoriesList")
                        .HasForeignKey("ProductsProductID");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Customrs", b =>
                {
                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Orders", null)
                        .WithMany("customrsList")
                        .HasForeignKey("OrdersOrderID");

                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.PaymentInformation", null)
                        .WithMany("customrsList")
                        .HasForeignKey("PaymentInformationPaymentID");

                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Reviews", null)
                        .WithMany("customrsList")
                        .HasForeignKey("ReviewsReviewID");

                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.ShippingAddresses", null)
                        .WithMany("customrsList")
                        .HasForeignKey("ShippingAddressesAddressID");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.OrderItems", b =>
                {
                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Orders", "orders")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Products", "products")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("orders");

                    b.Navigation("products");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Orders", b =>
                {
                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Customrs", "customers")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.OrderItems", null)
                        .WithMany("ordersList")
                        .HasForeignKey("OrderItemsOrderItemID");

                    b.Navigation("customers");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.PaymentInformation", b =>
                {
                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Customrs", "customers")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customers");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Products", b =>
                {
                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Categories", "categories")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.OrderItems", null)
                        .WithMany("productsList")
                        .HasForeignKey("OrderItemsOrderItemID");

                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Reviews", null)
                        .WithMany("productsList")
                        .HasForeignKey("ReviewsReviewID");

                    b.Navigation("categories");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Reviews", b =>
                {
                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Customrs", "customers")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Products", "products")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customers");

                    b.Navigation("products");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.ShippingAddresses", b =>
                {
                    b.HasOne("EntityFreamworkAssigment.E_Shop.Models.Customrs", "customers")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customers");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.OrderItems", b =>
                {
                    b.Navigation("ordersList");

                    b.Navigation("productsList");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Orders", b =>
                {
                    b.Navigation("customrsList");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.PaymentInformation", b =>
                {
                    b.Navigation("customrsList");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Products", b =>
                {
                    b.Navigation("categoriesList");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.Reviews", b =>
                {
                    b.Navigation("customrsList");

                    b.Navigation("productsList");
                });

            modelBuilder.Entity("EntityFreamworkAssigment.E_Shop.Models.ShippingAddresses", b =>
                {
                    b.Navigation("customrsList");
                });
#pragma warning restore 612, 618
        }
    }
}
